name: Node.js CI
on:
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    node-version: [12.x, 14.x, 17.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm test